import requests

baseurl = 'https://faas-nyc1-2ef2e6cc.doserverless.co/api/v1/web/fn-33d7e743-bdcf-4b28-8afd-5589d75e6700/uaibackend'


def GetJobOutput(jobId):
    """
    Get the Media Content generated by the job given a JobId
    
    Args:
        jobId (str): The JobId to get the output for
    
    Returns:
        media (dict): The json response from the server as {"media":[]}
    """
    url = baseurl+'/uaibackendgetjoboutput'
    data = {
        "job": jobId
    }
    r = requests.post(url, json=data)
    return r.json()


if  __name__ == "__main__":
    js = GetJobOutput("785ac784-6ebd-4634-8a2c-b40d27c5173e")
    print(js)